module SchnorrSig
  class Error < RuntimeError
  end
  class SizeError < Error
  end
  class TypeError < Error
  end
  class EncodingError < Error
  end

  def self.integer!: (untyped i) -> true
  def self.string!: (untyped str) -> true
  def self.bytestring!: (untyped str, untyped size) -> true

  def self.bin2big: (String str) -> Integer
  def self.big2bin: (Integer bignum) -> String
  def self.bin2hex: (String str) -> String
  def self.hex2bin: (String hex) -> String
end
