module SchnorrSig
  CONTEXT: Secp256k1::Context
  FORCE_32_BYTE_MSG: bool

  def self.strict_verify?: (String pk, String m, String sig) -> bool
  def self.key_pair: (String? sk) -> Secp256k1::KeyPair
  def self.signature: (String str) -> Secp256k1::SchnorrSignature
end
