module SchnorrSig
  class Error < RuntimeError
  end
  class SizeError < Error
  end

  def self.check!: (untyped val, Class cls) -> untyped
  def self.binary!: (String str, Integer length) -> String
  def self.bin2big: (String str) -> Integer
  def self.big2bin: (Integer bignum) -> String
  def self.bin2hex: (String str) -> String
  def self.hex2bin: (String hex) -> String
end
